services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/parkeasy
      - JWT_SECRET=secretkey
      - SESSION_SECRET=sessionsecret
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"